### ISSUE TITLE
Realm download fails with server

### ISSUE THREAD

**Issue by bakerq** [air/minecraft-tools#1]
On the first response command (line 19) we get the following response:

`http: error: SSLError: hostname 'mcoapi.minecraft.net' doesn't match '*.realms.minecraft.net'`

Currently the block of variables is set to:
```
backup_number="${1:-1}"
output_file=world.tar.gz
realms_server=https://mcoapi.minecraft.net
version=1.11.2

```
I've tried changing the version line to `version=1.12` but the error continues.

I've also tried changing the realms_server definition to `realms_server=https://realms.minecraft.net` but the error continues.

Just now I've tried changing both the version to 1.12 and the realm to `mcoapi.realms.minecraft.net` and I get:
`http: error: ConnectionError: HTTPSConnectionPool(host='mcoapi.realms.minecraft.net', port=443): Max retries exceeded with url: /worlds (Caused by <class 'socket.gaierror'>: [Errno -2] Name or service not known)`

I'm pretty sure the above is simply related to the lockouts from multiple attempts to run the command, but I've not confirmed that.  I have confirmed that I've run the "source login" command successfully.

**Comment by stop0xA** [comment]
I've had the same issue, it is due to a certificate issue. 
You can get around this by adding **--verify=no** to each http command inside realms_download.sh, put it between "http" and "--check-status

This is technically less secure, but as long as minecraft.net is still under mojangs control there should be no real problem.

**Comment by bakerq** [comment]
That took care of it, thank you!

**Comment by air** [comment]
I added this workaround to `realms-download.sh`. Thanks @bakerq for submitting and extra special thanks to @stop0xA for posting a fix!
I'd prefer to do everything by the book but since this isn't in the authentication flow I'm not too worried about verifying the cert.
